import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { Loader } from "@/components/loader";
import { ScrollReveals } from "@/components/helpers/scroll-reveals";
import { SmoothScroll } from "@/components/helpers/smooth-scroll";

const mont = Montserrat({
  variable: "--font-mont",
  subsets: ["latin"],
  weight: "variable",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${mont.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black text-white">
        {/* <Loader /> */}
        {/* <ScrollReveals /> */}
        {children}
      </body>
    </html>
  );
}
